//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saunov203.ApplicationDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Katalog
    {
        public int k_id { get; set; }
        public string k_artic { get; set; }
        public Nullable<int> k_katalog { get; set; }
        public string k_proiz { get; set; }
        public string k_post { get; set; }
        public Nullable<int> k_skid { get; set; }
        public Nullable<int> k_kolvo { get; set; }
        public string k_edinica { get; set; }
    
        public virtual Tovar Tovar { get; set; }
    }
}
