//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saunov203.ApplicationDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int r_id { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
