//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saunov203.ApplicationDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int t_id { get; set; }
        public string t_name { get; set; }
        public Nullable<decimal> t_cena { get; set; }
        public Nullable<int> t_skidka { get; set; }
        public string t_opisanie { get; set; }
        public string t_pictures { get; set; }
    
        public virtual Katalog Katalog { get; set; }
    }
}
