//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saunov203.ApplicationDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int U_Id { get; set; }
        public string U_F { get; set; }
        public string U_IO { get; set; }
        public string U_Login { get; set; }
        public string U_Password { get; set; }
        public Nullable<int> U_Role { get; set; }
    
        public virtual role role { get; set; }
    }
}
